// Server-only: Facebook Graph API publish call for the admin Social feature.
// No OAuth here -- the admin pastes a Page access token generated by hand at
// developers.facebook.com/apps (see src/routes/admin/social/connections.tsx),
// so this file is just the publish request, not a connect flow.
const GRAPH_VERSION = "v21.0";
const GRAPH_BASE = `https://graph.facebook.com/${GRAPH_VERSION}`;

type GraphError = { error?: { message?: string } };

async function graphPost(
  path: string,
  params: Record<string, string>,
): Promise<Record<string, unknown>> {
  const res = await fetch(`${GRAPH_BASE}${path}`, {
    method: "POST",
    body: new URLSearchParams(params),
  });
  const body = (await res.json()) as Record<string, unknown> & GraphError;
  if (!res.ok || body.error) {
    throw new Error(body.error?.message ?? `Facebook publish failed (${res.status})`);
  }
  return body;
}

export async function facebookPublish(
  pageId: string,
  pageAccessToken: string,
  caption: string,
  mediaUrl: string | null,
): Promise<{ remoteId: string }> {
  const params: Record<string, string> = { access_token: pageAccessToken };
  let path: string;
  if (mediaUrl) {
    path = `/${pageId}/photos`;
    params.url = mediaUrl;
    params.caption = caption;
  } else {
    path = `/${pageId}/feed`;
    params.message = caption;
  }
  const body = await graphPost(path, params);
  const remoteId = String(body.post_id ?? body.id ?? "");
  if (!remoteId) throw new Error("Facebook did not return a post id");
  return { remoteId };
}
