// Server-only: TikTok Content Posting API publish call for the admin Social
// feature. No OAuth here -- the admin pastes an access token generated by
// hand from their own TikTok developer app (see
// src/routes/admin/social/connections.tsx), so this file is just the publish
// request, not a connect flow.
const API_BASE = "https://open.tiktokapis.com/v2";

type TiktokErrorBody = { error?: { code?: string; message?: string }; error_description?: string };

async function tiktokPost<T>(path: string, body: Record<string, unknown>, accessToken: string) {
  const res = await fetch(`${API_BASE}${path}`, {
    method: "POST",
    headers: { "content-type": "application/json", authorization: `Bearer ${accessToken}` },
    body: JSON.stringify(body),
  });
  const json = (await res.json()) as T & TiktokErrorBody;
  const code = json.error?.code;
  if (!res.ok || (code && code !== "ok")) {
    throw new Error(
      json.error?.message ?? json.error_description ?? `TikTok API error (${res.status})`,
    );
  }
  return json;
}

export type TiktokVisibility = "private" | "public";

// Unaudited TikTok apps may only post privately (visible to the connected
// account only) -- "public" only actually works once the app has passed
// TikTok's Content Posting API review; TikTok itself rejects it otherwise.
function privacyLevel(visibility: TiktokVisibility): string {
  return visibility === "public" ? "PUBLIC_TO_EVERYONE" : "SELF_ONLY";
}

// TikTok caps the photo post_info.title at 90 chars (video allows more, but
// still isn't unlimited) -- the full caption goes in `description` instead
// (4000 char cap for photos), so a long product caption doesn't get rejected
// with "the request post info is empty or incorrect".
function truncate(s: string, max: number): string {
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

export async function tiktokPublish(
  accessToken: string,
  caption: string,
  mediaUrl: string,
  mediaType: "image" | "video",
  visibility: TiktokVisibility,
): Promise<{ publishId: string }> {
  const privacy_level = privacyLevel(visibility);
  const title = truncate(caption.split("\n")[0] || caption, mediaType === "video" ? 2200 : 90);
  const body =
    mediaType === "video"
      ? {
          post_info: { title, privacy_level },
          source_info: { source: "PULL_FROM_URL", video_url: mediaUrl },
        }
      : {
          post_mode: "DIRECT_POST",
          media_type: "PHOTO",
          post_info: { title, description: truncate(caption, 4000), privacy_level },
          source_info: { source: "PULL_FROM_URL", photo_images: [mediaUrl], photo_cover_index: 0 },
        };
  const json = await tiktokPost<{ data?: { publish_id?: string } }>(
    "/post/publish/content/init/",
    body,
    accessToken,
  );
  const publishId = json.data?.publish_id;
  if (!publishId) throw new Error("TikTok did not return a publish id");
  return { publishId };
}
